### PR TITLE
Make zoom downloader more user configurable

### PR DESCRIPTION
**Pull request by behanw**
Provide mechanisms to read more values from the config file.

- Allow configuration of download directory and completed meetings ids log file
- Allow configuration of start and end dates for downloading meetings
- Allow configuration of time format and timezone in meeting filenames
- Allow configuration of meeting filename and folder
- Allow for year/month/day to be used in filename/folder naming

### CODE REVIEW

**Comment by ricardorodrigues-ca** [comment]
@behanw before I merge, can you write up a quick readme on how to configure these values?

**Comment by behanw** [comment]
@ricardorodrigues-ca I should have done so the first time around. Apologies. Are these updates to the README file sufficient?

**Comment by behanw** [comment]
@ricardorodrigues-ca With the addition of updates to the README file I added to this pull request, is there any chance of getting this merged?

**Comment by ricardorodrigues-ca** [comment]
@behanw done!

**Pull request merged**
